status is-interactive; or exit

# Curated Git abbreviations. Keep common, composable operations and avoid
# shortcuts that hide destructive reset/clean commands.
abbr --add --global g git
abbr --add --global ga 'git add'
abbr --add --global gaa 'git add --all'
abbr --add --global gapa 'git add --patch'
abbr --add --global gb 'git branch -vv'
abbr --add --global gba 'git branch --all --verbose'
abbr --add --global gbd 'git branch --delete'
abbr --add --global gc 'git commit --verbose'
abbr --add --global 'gc!' 'git commit --verbose --amend'
abbr --add --global 'gcn!' 'git commit --no-edit --amend'
abbr --add --global gca 'git commit --verbose --all'
abbr --add --global gcm 'git commit --message'
abbr --add --global gcfx 'git commit --fixup'
abbr --add --global gcp 'git cherry-pick'
abbr --add --global gcpa 'git cherry-pick --abort'
abbr --add --global gcpc 'git cherry-pick --continue'
abbr --add --global gd 'git diff'
abbr --add --global gdca 'git diff --cached'
abbr --add --global gds 'git diff --stat'
abbr --add --global gf 'git fetch'
abbr --add --global gfa 'git fetch --all --prune'
abbr --add --global gl 'git pull'
abbr --add --global glr 'git pull --rebase'
abbr --add --global glo 'git log --oneline --decorate --color'
abbr --add --global glog 'git log --oneline --decorate --color --graph'
abbr --add --global gloga 'git log --oneline --decorate --color --graph --all'
abbr --add --global gm 'git merge'
abbr --add --global gma 'git merge --abort'
abbr --add --global gp 'git push'
abbr --add --global 'gp!' 'git push --force-with-lease'
abbr --add --global gpu 'git push --set-upstream origin (git branch --show-current)'
abbr --add --global grb 'git rebase'
abbr --add --global grba 'git rebase --abort'
abbr --add --global grbc 'git rebase --continue'
abbr --add --global grbi 'git rebase --interactive'
abbr --add --global grev 'git revert'
abbr --add --global grs 'git restore'
abbr --add --global grst 'git restore --staged'
abbr --add --global gsh 'git show'
abbr --add --global gsb 'git status --short --branch'
abbr --add --global gss 'git status --short'
abbr --add --global gst 'git status'
abbr --add --global gsta 'git stash push'
abbr --add --global gstl 'git stash list'
abbr --add --global gstp 'git stash pop'
abbr --add --global gsw 'git switch'
abbr --add --global gswc 'git switch --create'
abbr --add --global gwt 'git worktree'
abbr --add --global gwta 'git worktree add'
abbr --add --global gwtls 'git worktree list'
