# navi cheatsheet widget
# Ctrl+G is taken by ghq, so navi is mapped to Alt+N
if status is-interactive; and command -q navi
    # Generated by `navi widget fish`; kept inline to avoid launching navi on
    # every shell startup.
    function _navi_smart_replace
        set -l query (commandline --current-process | string trim)

        if test -n "$query"
            set -l best_match (navi --print --query "$query" --best-match)
            if test -n "$best_match"
                commandline --current-process $best_match
                return
            end
        end

        set -l candidate (navi --print --query "$query")
        test -n "$candidate"; and commandline --current-process $candidate
    end

    # Override navi's default Ctrl+G binding with Alt+N
    bind \en _navi_smart_replace
    if bind -M insert >/dev/null 2>/dev/null
        bind -M insert \en _navi_smart_replace
    end
    # Remove the Ctrl+G binding navi sets (ghq owns it)
    bind -e \cg 2>/dev/null
    bind -M insert -e \cg 2>/dev/null
end
