# @generated by usage-cli from usage spec

# if "usage" is not installed show an error
if ! type -P usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in mise." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end
set -l spec_dir (if set -q XDG_CACHE_HOME; echo $XDG_CACHE_HOME; else; echo $HOME/.cache; end)/usage
test -d "$spec_dir"; or mkdir -p -m 700 "$spec_dir"; or return
set -l spec_file "$spec_dir/usage__usage_spec_mise_2026_8_10.spec"
if not test -s "$spec_file"
    set -l generated_spec (mise usage)
    set -l mise_status $status
    test $mise_status -eq 0; or return $mise_status
    test (count $generated_spec) -gt 0; or return 1

    # Publish only a complete spec. Concurrent shells may generate identical
    # temporary files, but atomic rename prevents readers seeing partial data.
    set -l spec_tmp (mktemp --tmpdir="$spec_dir" '.usage__usage_spec_mise.XXXXXX'); or return
    string join \n -- $generated_spec >"$spec_tmp"
    command mv -- "$spec_tmp" "$spec_file"; or return
end

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc mise -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc mise -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
